### ISSUE TITLE
boolean_value_expression still in BNF

### ISSUE THREAD

**Issue by msdemlei** [ivoa-std/ADQL#32]
The BNF still mentions boolean_value_expression and all that's below it, including boolean_function, which isn't even defined.  I thought we wanted to drop all that?

**Comment by gmantele** [comment]
Dropping that would imply dropping the boolean type, no?

**Comment by msdemlei** [comment]
On Tue, Apr 21, 2020 at 02:17:19AM -0700, Grégory Mantelet wrote:
> Dropping that would imply dropping the boolean type, no?

Worse -- it would nuke search_condition.  So, I was overly rash,
confusing the matter with some other discussion we've had years ago,
and being blinded by the empty definition of boolean_function.

Still, I seem to remember we agreed that allowing booleans in too
many places made our grammar a lot more ambiguous without giving
proportional benefit.  For instance, we didn't want

```
  WHERE column_reference_to_boolean AND x<0
```

and also not

```
  WHERE boolean_function(a, b) OR x>0
```

and not even

```
  WHERE True or False
```

On the other hand, I think we wanted to allow

```
  WHERE True=ivo_hashlist_has('Optical', wavebands)
```

If that roughly reflects the consensus (and we may need to go back to
the mailing list archive to be sure), then here's what I think needs
to be done:

* remove boolean_value_expression from the alternatives of boolean_primary

* remove the entire boolean_value_expression rule

* remove the (currently empty) boolean_function rule

This ought to weed out the unwanted variants of the WHERE clause.

Then, to have the symbolic boolean literals (and to make good for our
removal of boolean_value_expression), we *could* replace
boolean_value_expression in the expansion of value_expression with
boolean_literal.

This certainly isn't optimal, as it allows things like 
WHERE False=True-1 (which would be True by current reckoning, and the
equivalent actually is True in python).  At least Postgres doesn't
let you do that; but then type errors don't need to be caught in the
grammar.  Still, I think it sucks.  I'd much prefer to just drop
boolean_value_expression from value_expression entirely.


An alternative I'd prefer would be to specifically have
boolean_comparisons, which might look like this:

```
boolean_comparison_operator ::= "="

boolean_comparison ::= 
  boolean_literal boolean_comparison_operator value_expression
  | value_expression boolean_comparison_operator boolean_literal 
```

and then have boolean_comparison be in predicate.  That would be
cleaner.  And you couldn't select it, for better or worse.

Now that I look at things, I find I've not actually done anything
about these in DaCHS yet.  I had come to essentially the current
conclusion in my Victoria (spring 2018) talk
(http://wiki.ivoa.net/internal/IVOA/InterOpMayy2018DAL/adql21-issues.pdf)
but then had forgotten about it.

It's a relatively high price to pay for a rather silly piece of
syntactic sugar, but there you go.

I'd not veto dropping the boolean literals altogether.

**Comment by Zarquan** [comment]
> Still, I seem to remember we agreed that allowing booleans in too many places made our grammar a lot more ambiguous without giving proportional benefit. For instance, we didn't want

It has been a while and I can't remember the details of what was decided on this. Could you post a href to the mailing list discussion.

**Comment by Zarquan** [comment]
> WHERE True=ivo_hashlist_has('Optical', wavebands)

I do remember that a lot of our users complained about having to use

    WHERE True=function()

and we were trying to gradually add things like boolean type so that eventually we would be able to support

    WHERE function()

**Comment by msdemlei** [comment]
On Wed, Apr 22, 2020 at 03:13:55AM -0700, Zarquan wrote:
> > WHERE True=ivo_hashlist_has('Optical', wavebands)
> 
> I do remember that a lot of our users complained about having to use
> 
>     WHERE True=function()
> 
> and we were trying to gradually add things like boolean type so that eventually we would be able to support
> 
>     WHERE function()

Well, I agree this would be nice to have, but when you try to
implement that you notice that the grammar of the where clause
becomes a lot "less regular" (in the language-theoretical sense),
which in turn means that producing good error messages becomes still
more of a problem.

This could be avoided by having keywords for the most common cases;
but then I think once people write DISTANCE rather than CONTAINS,
most of these complaints will vanish anyway.

As to previous discussions, I think all that's on record is the
abortive

http://mail.ivoa.net/pipermail/dal/2018-March/007985.html

I have vague memories of raising the point in person on one or two
occasions and getting the feeling nobody really champions going for
boolean all the way.  The fact that nobody felt strongly about the
DAL thread is perhaps another indication that the thing isn't worth a
lot of effort.  Which again raises the question if having the True
and False literals is actually worth it, given they open a can of
worms.

**Comment by Zarquan** [comment]
Yep, I agree. This goes back a loong way, back to the TAP implementation notes in 2014.
https://volute.g-vo.org/svn/trunk/projects/dal/TAPNotes/TAPNotes-fmt.html#af-booleans

However, not having a strong decision either way

>  nobody really champions going for boolean all the way. The fact that nobody felt strongly about the DAL thread is perhaps another indication that the thing isn't worth a lot of effort.

 is not the same as saying

>  we agreed that allowing booleans in too many places made our grammar a lot more ambiguous without giving proportional benefit.

**Comment by Zarquan** [comment]
How important is it to get the 2.1 BNF absolutely 100% right ?

Bear in mind we are planning to replace BNF with PEG as soon as we move on to version 3.x. Is this something that will be easier to solve in PEG ? Can we come up with something that is _'good enough for now'_, get 2.1 out the door, and then revisit it in version 3.x ?

**Comment by msdemlei** [comment]
On Thu, Apr 23, 2020 at 04:55:00AM -0700, Zarquan wrote:
> How important is it to get the 2.1 BNF absolutely 100% right ?

Well, what are people supposed to implement against?  Empty BNF
expansions are certainly a no-no in my book.  Overgenerating rules
are a bad pain, too, because people will later have to decide whether
that was on purpose or is an erratum (cf. the parallel discussion on
coord_sys).

Undergenerating rules are perhaps not as bad, because it's always
easier to allow more things than to forbid things that were allowed
before.

Rules that generate something that nobody wants: What would be the
point?

But then: If nobody cares enough about a feature to provide correct
BNF, then why put it in in the first place?

> Bear in mind we are planning to replace BNF with PEG as soon as we
> move on to version 3.x. Is this something that will be easier to
> solve in PEG ? Can we come up with something that is _'good enough
> for now'_, get 2.1 out the door, and then revisit it in version 3.x?

The problem at hand is completely independent of the grammar
syntax chosen, so it'll be exactly the same in 2.2 (or 3.0, if that's
what it takes).

Since right now there don't seem to be any implementations of the
whole boolean literal thing, on a bit more contemplation I'd (still)
say: let's drop it altogether for 2.1 -- it just doesn't seem to be
all that important.

(and apologies for mis-remembering "nobody cared much" as "all who
cared agreed to let it go")

**Comment by Zarquan** [comment]
So, we back to here again .. do we want to be able to replace

    WHERE 1 = CONTAINS(...)

with the simpler and more understandable (for the user)

    WHERE CONTAINS(...)

at the cost of more complications for the service developers

- Dave (@Zarquan) says yes, but doesn't have the resources to implement it 
- http://mail.ivoa.net/pipermail/dal/2018-March/007992.html

- I think Markus (@msdemlei) says no, and would prefer to keep ADQL simple
- https://wiki.ivoa.net/internal/IVOA/InterOpMayy2018DAL/adql21-issues.pdf

- Neither of us has managed to convince many others of the merits of our positions
- No comment from the community just means they are bored.

How do we move forward ? Do we schedule a discussion at the interop meeting ? Will that help solve it ?

Does anyone else think 

    WHERE CONTAINS(...)

is worth the effort ? 

If there is no support for this, then I withdraw my objections.

**Comment by gmantele** [comment]
While implementing ADQL, I personnaly rely a lot on the BNF....more than on the text. After all, it is the grammar as a machine is supposed to understand it. Having the BNF as much as possible right is then important. It is even more important because it prevents different human interpretations of the text based on the implementors' experience in matter of SQL. Examples of such interpretation difference are the coord_sys, expressions or just columns and indexes in ORDER BY, etc... Moreover, if the BNF is not right how do we know if the PEG grammar we will propose is specifying the same grammar? The BNF is the main source of inspiration for the PEG grammar to come.

----

Coming back to the boolean_value_expression issue, I am really shared between my user experience and my implementor one. As user, no discussion on the fact that I prefer to write `CONTAINS(...)` rather than `True=CONTAINS(...)`. But as implementor, I have to admit being sensible to the Markus comments. Because of this shared feeling, I have not said anything before now.

I see at least 3 difficulties, apart from the Markus arguments about the grammar:

- the boolean type is not supported in all DBMS => special translation into SQL required (i.e. appending of '= 1' or '= 0') => identification of a boolean expression absolutely required by the ADQL parser => not trivial, as Markus said

- 'boolean' is defined as equivalent to a numeric (0=False, 1=True) => a numeric is a boolean expression => a boolean can be interpreted as a numeric => more ambiguity in the grammar (a boolean could be used where a numeric would be...more type inference is needed, making the parser more complex and so more error prone)

- in 2.x, CONTAINS(...) and INTERSECTS(...) return a numeric (0 or 1), not a boolean ; 3.x should make them return a boolean value

------

According to me, here are the options (+ all possible ways to write the same query) we have to resolve this issue:

1. Keep the current proposition with boolean value expressions...and "cross-fingers" in implementations

   ```sql
   SELECT * FROM atable WHERE CONTAINS(...) OR column_boolean OR boolean_udf(...)
   SELECT * FROM atable WHERE 1=CONTAINS(...) OR 1=column_boolean OR 1=boolean_udf(...)
   SELECT * FROM atable WHERE True=CONTAINS(...) OR True=column_boolean OR True=boolean_udf(...)
   ```
   
2. Keep the boolean type but force `= True` or `= False` as a normal comparison
    - in 3.0: CONTAINS and INTERSECTS will return a boolean so that the `= True` or `= False` are not required anymore + no more boolean-numeric equivalence

   ```sql
   SELECT * FROM atable WHERE 1=CONTAINS(...) OR 1=column_boolean OR 1=boolean_udf(...)
   SELECT * FROM atable WHERE True=CONTAINS(...) OR True=column_boolean OR True=boolean_udf(...)
   ```
   
3. Keep the boolean type but no numeric equivalence _(preparation for ADQL-3.0)_
   - CONTAINS and INTERSECTS must still be compared to `= 1` and `= 0` in 2.1 ; in 3.0, they will return a boolean
   - possible to write `WHERE column_boolean OR my_boolean_udf(...)`
   
   ```sql
   SELECT * FROM atable WHERE 1=CONTAINS(...) OR column_boolean OR boolean_udf(...)
   SELECT * FROM atable WHERE 1=CONTAINS(...) OR True=column_boolean OR True=boolean_udf(...)
   ```
   
5. No boolean

   ```sql
   SELECT * FROM atable WHERE 1=CONTAINS(...) OR 1=column_boolean OR 1=boolean_udf()
   ```

If we go for keeping the boolean type, I would prefer (in that order) 3 and 2. I agree with Markus than 1 introduce implementation difficulties prone to parsing errors.

Then, I am not sure the boolean type is the most important thing to work on in ADQL...right now. Does it worth having boolean in 2.1? Currently I would say 'no' ; I think me, and users too, can live without it for the moment...as we did until now. If we choose to have boolean types from 2.1, I would avoid going too fast because as said Markus:

> it's always easier to allow more things than to forbid things that were allowed before.

**Comment by msdemlei** [comment]
On Thu, Apr 23, 2020 at 08:48:21AM -0700, Grégory Mantelet wrote:
> According to me, here are the options (+ all possible ways to write
> the same query) we have to resolve this issue:
> 
> [...]

There is a sixth one, and that is that we have predicate-valued
functions with specific keywords.  That is: there are no boolean
literals as such, but we could write

```
<predicate> ::=
  (as now)
  | <geometry_predicate>

<geometry_predicate> ::=
  <contains>
  | <intersects>
```

Having thought just briefly about it, I *think* that would work with
the current grammar if all people want is to save the 1= thing, and
it wouldn't spoil the grammar much.

But again: I think once everyone moves to DISTANCE, I guess the point
is largely moot.

So yes, as Dave suspects, I'd really prefer Grégory's option 5: don't
do anything boolean-related at all.
