### ISSUE TITLE
Add a license (as per IVOA recommendation)

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ADQL#7]

**Comment by molinaro-m** [comment]
nice case. there's a typo in the  issue title, can I fix it harmlessly as a user?

**Comment by olebole** [comment]
I think only the issue author and the repo owner can change this.

**Comment by molinaro-m** [comment]
So I won't try it, falling in the last role.

**Comment by olebole** [comment]
If there is the "Edit" button next to the title, you can do it.

**Comment by gmantele** [comment]
Is there any kind of IVOA agreement on which license to use?

If Creative Commons, **CC BY-SA**?
_(description on <https://creativecommons.org/licenses/by-sa/4.0/>, and text of the README.txt to include so that being clearly identified by GitHub: <https://choosealicense.com/licenses/cc-by-sa-4.0/>)_

If yes, I can prepare the corresponding Pull Request right now.

**Comment by molinaro-m** [comment]
There has been some agreement on the license both at TCG and Exec levels. Nothing 100% sure, I must admit.
At least for document's source it shouldn't be an issue and the license should be CC-BY-SA as you mention.
The license should be in the repo, of course, but possibly also reported in the document, maybe in the "Status of the Document" section.

So, I suppose you can freely branch this issue, but I wonder if its subsequent merge will take a bit longer than expected.

**Comment by gmantele** [comment]
_Solved by Pull Request #14 (approved and merged)_
