### ISSUE TITLE
ADQL 2.1 version identifier definition

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ADQL#76]
TAPRegExt v1.0 and v1.1 define the identifier `ivo://ivoa.net/std/ADQL#v2.0` as the value of the `capabilities/capability/language/version/@ivo-id` attribute in a TAP capabilities document to indicate support of ADQL 2.0.  Presumably the corresponding value for support of ADQL 2.1 would be `ivo://ivoa.net/std/ADQL#v2.1`, but I don't see that definition anywhere.  Should it be included in this document?  And if not, where?

**Comment by gmantele** [comment]
I have to say that I am still very confused with the version number of a standard in an IVOID. I kind of recall that there were a lot of discussions saying that the version number must be in and others saying the opposite.

An external opinion (from let's say registry experts) would be welcome here.

**Comment by mbtaylor** [comment]
Markus's StandardsRegExt file at #77 answers this - thanks. Arguably the ID or IDs could be mentioned in the text as well, but I don't think it's essential.

**Comment by msdemlei** [comment]
On Thu, Mar 23, 2023 at 10:07:43AM -0700, Grégory Mantelet wrote:
> I have to say that I am still very confused with the version number
> of a standard in an IVOID. I kind of recall that there were a lot
> of discussions saying that the version number must be in and others
> saying the opposite.

Well, that's because we have never really worked out when and (most
of all) why we would like to expose minor versions.  And what clients
are expected to do with them.  Me, I tend to suggest that we should
hide minor versions as well as we can -- after all, that's why
they're *minor*.  And feature discovery should IMHO almost always use
some other means than looking at minor versions.

But, ah well, a former self of mine has been dumb^Wshortsighted
enough to have put the following into TAPRegExt 1.0:

  The IVORN for the only language mandatory for TAP services, ADQL
  2.0, is ivo://ivoa.net/std/ADQL#v2.0.

I'm not sure if anyone actually has used these ivoids in all these
years.  I'd submit that ***@***.*** is plenty, and
***@***.*** is more than plenty.

In that sense, we could just drop the stupid ivoids of ADQL in
TAPRegExt 1.1 and not bother with them any more, in particular not
bother within ADQL.  You'd have my vote.  Perhaps we should make a
quick post on the DAL list stating we're planning to do that and
folks who'd miss the ivoids should speak up.

Having said all that, the nasty ADQL 2.0 ivoid is there, in all its
dangerous mixed-case glory (ivoids are, sigh, case-insensitive).  And
hence it would be good if it resolved.  To make that happen, ADQL
needs a StandardsRegExt record in the RofR.  I'm surprised I never
noticed that that is still missing.

I'd suggest we rectify that (technically irrelevant) oversight when
we go to PR with ADQL 2.1.  For that purpose, PR #77 adds such a record.
You ought to update the date when you prepare the PR.  The submission
checklist
https://ivoa.net/documents/Notes/IVOATexDoc/20220525/NOTE-ivoatexDoc-1.3-20220525.html#tth_sEc3.12
will remind you to do that.

**Comment by mbtaylor** [comment]
I might be misunderstanding the issue here, but to me the minor version declared in the capabilities document of a TAP service is certainly useful.  When parsing ADQL that a user wants to submit to a TAP service, I can look at the ADQL version supported by that service as declared by the TAPRegExt `language/version/@ivo-id` attribute, and pass that to Gregory's ADQL parser to decide what syntax is permitted in the query.  I suppose I could use the `language` element text content instead of the `ivoid` attribute - is that what you're suggesting as "some other means" of feature discovery?

**Comment by msdemlei** [comment]
On Fri, Mar 24, 2023 at 03:58:20AM -0700, Mark Taylor wrote:
> service as declared by the TAPRegExt ***@***.***`
> attribute, and pass that to Gregory's ADQL parser to decide what
> syntax is permitted in the query.  I suppose I could use the
> `language` element text content instead of the `ivoid` attribute -

Ok, so that settles it already.  If you're using ivoid and you're
happy to do that instead of looking at language/version, that's
reason enough for me to keep and maintain them (just make sure you
compare case-insensitively).

> is that what you're suggesting as "some other means" of feature
> discovery?

No, this may be one of the cases where inspecting minor versions is
actually what you want to do (indeed, tasks somewhere in the vicinity
of validation are where I've found most credible applications for
minor-sharp version specs so far).

What I had in mind as "other means" is more things like explicit
declarations of features, listing of input parameters supported,
content negotiation, or fallbacks of the type "ignore anything you
don't understand".

**Comment by gmantele** [comment]
It seems indeed like a good use case for including minor versions in the IVOID.

**Comment by gmantele** [comment]
To come back to the ADQL document, it would make sense to write this IVOID with the minor version (and in full lower case) somewhere. This way, any ADQL compatible standard could define which versions it does support with the same well-defined IVOID.

Currently only TAP makes use of ADQL and so, it seems sensefull to define the IVOID to use in its capabilities. But what if another standard appears or if an existing one is updated and uses ADQL too? Should it also define the IVOID for ADQL? I think that giving to ADQL compatible standards the responsibility to define the IVOID to use for ADQL is more error prone (e.g. possible duplication with out-dated ADQL version definition).

Another solution would be to define it in another Registry document dedicated to list valid IVOIDs. Is there any? _(sorry for having no registry knowledge at all)_

If not, it is probably best to define this IVOID in the ADQL document. Possibly a text like below (in a third appendix):

> **Appendix C: ADQL capability**
>
> Any standard making use of ADQL can declare this capability with the following IVOID:
> ```
>     ivo://ivoa.net/std/adql
> ```
>
> A specific ADQL version MAY be specified with a hash parameter following one of these syntax:
> * `vx` for the latest minor revision of the major ADQL version `x`
> * `vx.y` for a specific minor ADQL revision
>
> When no version is specified, the latest ADQL version is expected to be supported.
>
> Examples of valid IVOID:
> ```
>     ivo://ivoa.net/std/adql
>     ivo://ivoa.net/std/adql#v2
>     ivo://ivoa.net/std/adql#v2.1
> ```

If this is OK with you, I prepare the appropriate PullRequest for this.

**Comment by Zarquan** [comment]
I agree. The IVOID ended up in the TAP document because of history, but you are right it should be in the ADQL document.

**Comment by msdemlei** [comment]
On Fri, Mar 24, 2023 at 06:11:09AM -0700, Grégory Mantelet wrote:
> To come back to the ADQL document, it would make sense to write
> this IVOID with the minor version (and in full lower case)

That's probably true, yes.

> Another solution would be to define it in another Registry document
> dedicated to list valid IVOIDs. Is there any? _(sorry for having no
> registry knowledge at all)_

The list of all valid IVOIDs is called the Registry :-)

More seriously, to see if an IVOID is valid, you can simply run a
RegTAP query such as

  SELECT ivoid FROM rr.resource WHERE ivoid='ivo://ivoa.net/std/adql'

(note the lower case; this assumes that we don't let syntactically
bad IVOIDs in, which we probably would, but cut me some slack there).
When fragments (such as the "#v2.1") come into play, things become a
bit more complicated, but that's beyond the point here.

> If not, it is probably best to define this IVOID in the ADQL
> document. Possibly a text like below (in a third appendix):
>
> > **Appendix C: ADQL capability**

Frankly, I feel an extra appendix would be rather heady-handed for
this relatively minor thing.

> > Any standard making use of ADQL can declare this capability with the following IVOID:
> > ```
> >     ivo://ivoa.net/std/adql
> > ```
> >
> > A specific ADQL version MAY be specified with a hash parameter
> > following one of these syntax:

Nah, if we go into all this trouble, let's require version-sharp
references.

> If this is OK with you, I prepare the appropriate PullRequest for this.

Since I'm rather unhappy with an extra appendix, I looked for a
better place of the ivoid, and while doing this I noticed that the
architecture section was still in a bad shape (ancient and outdated
role diagram, no explanatory text).  I've hence made a stab at
improving matters in that department, and I think that is a
reasonable place for the IVOID, too, because as far as ADQL itself
goes, it only matters in relation to other standards.

So, I'd propose #80 as an (exclusive) alternative to #79.

I'd be happy to amend the list of relationships of ADQL if you think
we should have more relationships…

**Comment by gmantele** [comment]
Ok for #80

**Comment by gmantele** [comment]
Fixed with #80 merged
